### ISSUE TITLE
Add ability for multiple notebooks improvement 

### ISSUE THREAD

**Issue by OliverFishCode** [Recollectr/releases#2]
Would be nice to have notes be in separate notebooks? I.e. one for personal notes and one for  work.

**Comment by Recollectr** [comment]
Hey @OliverFishCode - Thanks for your suggestion! 

I know you already saw our response on Reddit, but for anyone else, [you can read it here](https://www.reddit.com/r/Recollectr/comments/c4ibbr/feature_request_multiple_notebooks/).

TL;DR: We'll likely support a `Work` and `Personal` notebook in the future
